INFO     core.mock_http_client:mock_http_client.py:24 MockHTTPClient ID 139851026919312 инициализирован. Mocks: {}
INFO     tests.auth.test_auth_mocked:test_auth_mocked.py:126 Тест: Серверная ошибка (Мок Factory)
INFO     core.mock_http_client:mock_http_client.py:108 MockHTTPClient ID 139851026919312 установил мок для: 'POST:/api/auth' (Статус: 500). Текущие моки: ['POST:/api/auth']
INFO     core.mock_http_client:mock_http_client.py:36 MockHTTPClient ID 139851026919312 ищет мок для ключа: 'POST:/api/auth'. Текущие моки: ['POST:/api/auth']
INFO     core.mock_http_client:mock_http_client.py:44 Найден и возвращен мок для: POST:/api/auth
INFO     tests.auth.test_auth_mocked:test_auth_mocked.py:142 Мок-ответ 500 (серверная ошибка) успешно обработан.
INFO     core.mock_http_client:mock_http_client.py:118 MockHTTPClient ID 139851026919312 очищает моки. Было: ['POST:/api/auth']